Tempo_Total = 
SUMX(
    DataSourceConnection, 
    DATEDIFF(
        DataSourceConnection[dtInicio], 
        IF(ISBLANK(DataSourceConnection[dtFimAtualizado]), TODAY(), DataSourceConnection[dtFimAtualizado]), 
        DAY
    )
)
